version: '3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
  odoo:
    build: .
    ports:
      - '8069:8069'
    volumes:
      - './odoo:/bitnami/odoo'
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ODOO_CORS_ORIGIN=*
      - ODOO_CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      - ODOO_HTTP_HEADERS=Content-Type,Authorization,Origin,X-Requested-With,X-Frame-Options,X-CSRF-Token
      - ODOO_ACCESS_CONTROL_ALLOW_ORIGIN=*
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
