version: '3.8'

volumes:
  postgres_data: {}

services:
  postgres:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
